### ISSUE TITLE
Delta pull fails with "rsync exited. code: 30 signal: null"

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/node-docker-delta#10]
A user reported that a freshly provisioned device with deltas set at provision time failed with this error:
`rsync exited. code: 30 signal: null`
Looking in the supervisor logs the only error I saw was this:

```
Oct 05 15:23:48 raspberrypi3 bash[467]: [2016-10-05T15:23:48.954Z] Will not set boot config:  Error: Nothing to change
Oct 05 15:23:48 raspberrypi3 bash[467]: at /usr/src/app/src/device.js:170:17
Oct 05 15:23:48 raspberrypi3 bash[467]: at eval (eval at caller (/usr/src/app/node_modules/bluebird/js/main/join.js:23:16), <anonymous>:6:20)
Oct 05 15:23:48 raspberrypi3 bash[467]: at tryCatcher (/usr/src/app/node_modules/bluebird/js/main/util.js:26:23)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Holder.checkFulfillment (/usr/src/app/node_modules/bluebird/js/main/join.js:51:40)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Promise.eval (eval at thenCallback (/usr/src/app/node_modules/bluebird/js/main/join.js:13:16), <anonymous>:6:20)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Promise._settlePromiseAt (/usr/src/app/node_modules/bluebird/js/main/promise.js:582:21)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/main/promise.js:700:14)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Async._drainQueue (/usr/src/app/node_modules/bluebird/js/main/async.js:123:16)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/main/async.js:133:10)
Oct 05 15:23:48 raspberrypi3 bash[467]: at Immediate.Async.drainQueues (/usr/src/app/node_modules/bluebird/js/main/async.js:15:14)
Oct 05 15:23:49 raspberrypi3 bash[467]: at runCallback (timers.js:574:20)
Oct 05 15:23:49 raspberrypi3 bash[467]: at tryOnImmediate (timers.js:554:5)
Oct 05 15:23:49 raspberrypi3 bash[467]: at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by dfunckt** [comment]
code 30 is `Timeout in data send/receive`

**Comment by pcarranzav** [comment]
Yeah, this is due to a timeout, probably because of a bad network. https://github.com/resin-io/node-docker-delta/pull/17 should mitigate it a bit, but it'd be nice to find a way to make this more resilient to bad network conditions

**Comment by dfunckt** [comment]
#19 removed the rsync timeout completely and we now handle it ourselves -- we'll now start retrying the actual request (see https://github.com/resin-io-modules/resumable-request/pull/2) and manually force rsync to exit a certain timeout after the connection closes. This means we're going to handle bad network before rsync even notices, so this error should not appear again.

I'm tentatively closing the issue -- feel free to reopen.
